import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/providers/themeProvider";
import { cn } from "@/lib/utils";
import ModalProvider from "@/components/providers/modalProvider";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Discord clone",
  description: "Generated by Mehdi Znayzen",
  icons : "/images/discord_logo.png"
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
          <body className={cn(font.className, 'bg-white dark:bg-[#313338]')}>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              storageKey="discord-clone"
            >
              <ModalProvider />
              {children}
            </ThemeProvider>
          </body>
      </html>
    </ClerkProvider>
  );
}
